# Generated by Django 3.2.10 on 2023-11-04 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_cart_user'),
        ('cart', '0002_initial'),
    ]

    operations = [
    ]
