# Generated by Django 3.2.10 on 2023-11-04 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_initial'),
        ('order', '0003_auto_20231103_0710'),
    ]

    operations = [
    ]
