import pandas as pd

user_data_rinnai = [
    (26, "muhammad risfandanu", "muhammad_risfandanu@gmail.com"),
    (27, "adnil riza", "adnil_riza@gmail.com"),
    (28, "nadia gustiana", "nadia_gustiana@gmail.com"),
    (29, "nanda aditya", "nanda_aditya@gmail.com"),
    (30, "nurgivo alfajri", "nurgivo_alfajri@gmail.com"),
    (66, "fadana bagus harsono", "fadana_bagus_harsono@gmail.com"),
    (67, "rahmi omya ulta", "rahmi_omya_ulta@gmail.com"),
    (68, "rahmi septhianingrum", "rahmi_septhianingrum@gmail.com"),
    (69, "rangga arief putra", "rangga_arief_putra@gmail.com"),
    (70, "rangga dwi nugrawan", "rangga_dwi_nugrawan@gmail.com"),
    (106, "raynaldi setiawan", "raynaldi_setiawan@gmail.com"),
    (107, "shynta dwi afitri", "shynta_dwi_afitri@gmail.com"),
    (108, "siti romlah", "siti_romlah@gmail.com"),
    (109, "teresno maulana", "teresno_maulana@gmail.com"),
    (110, "tessa eka fatiwi", "tessa_eka_fatiwi@gmail.com"),
    (146, "thovanni jogga", "thovanni_jogga@gmail.com"),
    (147, "tian fitra kurniawan", "tian_fitra_kurniawan@gmail.com"),
    (148, "widya ayu azhari", "widya_ayu_azhari@gmail.com"),
    (149, "yudiatma adrion", "yudiatma_adrion@gmail.com"),
    (150, "zukri rahman", "zukri_rahman@gmail.com"),
    (186, "yulia ningsih", "yulia_ningsih@gmail.com"),
    (187, "anggia anfina", "anggia_anfina@gmail.com"),
    (188, "anita pauzia hsb", "anita_pauzia_hsb@gmail.com"),
    (189, "annisa julita sari", "annisa_julita_sari@gmail.com"),
    (190, "boby adi oktarino", "boby_adi_oktarino@gmail.com"),
    (226, "asri jakawendra", "asri_jakawendra@gmail.com"),
    (227, "astri stiawaty", "astri_stiawaty@gmail.com"),
    (228, "aszani", "aszani@gmail.com"),
    (229, "boby rahman", "boby_rahman@gmail.com"),
    (230, "dewi cahyati", "dewi_cahyati@gmail.com"),
    (266, "donna febriani", "donna_febriani@gmail.com"),
    (267, "dwi widiastuti", "dwi_widiastuti@gmail.com"),
    (268, "dwiki apsyarin", "dwiki_apsyarin@gmail.com"),
    (269, "dwiza indri", "dwiza_indri@gmail.com"),
    (270, "frans b jaya zalukhu", "frans_b_jaya_zalukhu@gmail.com"),
    (306, "adelia agustin", "adelia_agustin@gmail.com"),
    (307, "desi aulia rahma", "desi_aulia_rahma@gmail.com"),
    (308, "muhammad fajar maulana", "muhammad_fajar_maulana@gmail.com"),
    (309, "muliadi", "muliadi@gmail.com"),
    (310, "nuriyati", "nuriyati@gmail.com"),
    (346, "daryono", "daryono@gmail.com"),
    (347, "poniyem", "poniyem@gmail.com"),
    (348, "fajar setiawan", "fajar_setiawan@gmail.com"),
    (349, "nabilatul dwi seftiani", "nabilatul_dwi_seftiani@gmail.com"),
    (350, "jaimin", "jaimin@gmail.com"),
    (386, "warsini", "warsini@gmail.com"),
    (387, "alif al barrak zaki", "alif_al_barrak_zaki@gmail.com"),
    (388, "sulistiyono", "sulistiyono@gmail.com"),
    (389, "jekri wiralis", "jekri_wiralis@gmail.com"),
    (390, "nirmanto", "nirmanto@gmail.com"),
    (426, "kasturi", "kasturi@gmail.com"),
    (427, "epran", "epran@gmail.com"),
    (428, "suwarsih", "suwarsih@gmail.com"),
    (429, "dwi astika sari", "dwi_astika_sari@gmail.com"),
    (430, "trio hamdani", "trio_hamdani@gmail.com"),
    (466, "sazim saputra", "sazim_saputra@gmail.com"),
    (467, "rozakiah", "rozakiah@gmail.com"),
    (468, "alifia yuliani", "alifia_yuliani@gmail.com"),
    (469, "hamzah maulana", "hamzah_maulana@gmail.com"),
    (470, "akbar maulana", "akbar_maulana@gmail.com"),
    (506, "tri lestari", "tri_lestari@gmail.com"),
    (507, "kurniawan zam zami", "kurniawan_zam_zami@gmail.com"),
    (508, "raditia saputri", "raditia_saputri@gmail.com"),
    (509, "mabruro", "mabruro@gmail.com"),
    (510, "mukaromah", "mukaromah@gmail.com"),
    (546, "sanmiadi watimin", "sanmiadi_watimin@gmail.com"),
    (547, "sakiyah", "sakiyah@gmail.com"),
    (548, "ahmad soleh", "ahmad_soleh@gmail.com"),
    (549, "nurfajri", "nurfajri@gmail.com"),
    (550, "sri kasanah", "sri_kasanah@gmail.com"),
    (586, "naimatul masruboh", "naimatul_masruboh@gmail.com"),
    (587, "siti arifatul fu'adah", "siti_arifatul_fu'adah@gmail.com"),
    (588, "suendik", "suendik@gmail.com"),
    (589, "wiwin herlina", "wiwin_herlina@gmail.com"),
    (590, "saputra", "saputra@gmail.com"),
    (626, "suritno", "suritno@gmail.com"),
    (627, "susanti", "susanti@gmail.com"),
    (628, "m. sarengat", "m._sarengat@gmail.com"),
    (629, "sumari", "sumari@gmail.com"),
    (630, "suminten", "suminten@gmail.com"),
    (666, "suparno", "suparno@gmail.com"),
    (667, "dewi fitria", "dewi_fitria@gmail.com"),
    (668, "hadista nadratul zanah", "hadista_nadratul_zanah@gmail.com"),
    (669, "rafkan djovanka al fariz", "rafkan_djovanka_al_fariz@gmail.com"),
    (670, "volint", "volint@gmail.com"),
    (706, "lilik mujiati", "lilik_mujiati@gmail.com"),
    (707, "shofiyyatun dzakiroh", "shofiyyatun_dzakiroh@gmail.com"),
    (708, "wulan maratussholikha", "wulan_maratussholikha@gmail.com"),
    (709, "aris tiono", "aris_tiono@gmail.com"),
    (710, "sitti julaeha", "sitti_julaeha@gmail.com"),
    #
    (746, "aziz", "aziz@gmail.com"),
    (747, "suyoto", "suyoto@gmail.com"),
    (748, "binar", "binar@gmail.com"),
    (749, "alek susanto", "alek_susanto@gmail.com"),
    (750, "aris setianto", "aris_setianto@gmail.com"),
    (786, "rubini", "rubini@gmail.com"),
    (787, "pursito", "pursito@gmail.com"),
    (788, "rita fitri mulyasih", "rita_fitri_mulyasih@gmail.com"),
    (789, "saikun", "saikun@gmail.com"),
    (790, "sutiti", "sutiti@gmail.com"),
    (826, "sutiono", "sutiono@gmail.com"),
    (827, "listiani", "listiani@gmail.com"),
    (828, "m. ikhwan amsyahputra", "m._ikhwan_amsyahputra@gmail.com"),
    (829, "anindita keisha azzahra", "anindita_keisha_azzahra@gmail.com"),
    (830, "joni kartinus", "joni_kartinus@gmail.com"),
    (866, "muhammad albana", "muhammad_albana@gmail.com"),
    (867, "salwa unaisah", "salwa_unaisah@gmail.com"),
    (868, "harun fadhillah", "harun_fadhillah@gmail.com"),
    (869, "salma nusaybah", "salma_nusaybah@gmail.com"),
    (870, "shoffan al fath", "shoffan_al_fath@gmail.com"),
    (906, "rudianto", "rudianto@gmail.com"),
    (907, "siswanto", "siswanto@gmail.com"),
    (908, "titin fatimah", "titin_fatimah@gmail.com"),
    (909, "nanda lucky firmansyah", "nanda_lucky_firmansyah@gmail.com"),
    (910, "zulvan arfa syazwan", "zulvan_arfa_syazwan@gmail.com"),
    (946, "srini", "srini@gmail.com"),
    (947, "yeni purwaningsih", "yeni_purwaningsih@gmail.com"),
    (948, "vebri kurniawan", "vebri_kurniawan@gmail.com"),
    (949, "ahmad diinulkha", "ahmad_diinulkha@gmail.com"),
    (950, "didik siswanto", "didik_siswanto@gmail.com"),
    (986, "choiriyah", "choiriyah@gmail.com"),
    (987, "sagiman", "sagiman@gmail.com"),
    (988, "sutinah", "sutinah@gmail.com"),
    (989, "elisnawati", "elisnawati@gmail.com"),
    (990, "winda aprilia", "winda_aprilia@gmail.com"),
    (1026, "aila annafi'an zaini", "aila_annafi'an_zaini@gmail.com"),
    (1027, "novi ayu sharafina", "novi_ayu_sharafina@gmail.com"),
    (1028, "nova ayu sharafika", "nova_ayu_sharafika@gmail.com"),
    (1029, "samsuri", "samsuri@gmail.com"),
    (1030, "ani", "ani@gmail.com"),
    (1066, "hadi wagiman", "hadi_wagiman@gmail.com"),
    (1067, "suparmi", "suparmi@gmail.com"),
    (1068, "sigit widianto", "sigit_widianto@gmail.com"),
    (1069, "singgih adi putra", "singgih_adi_putra@gmail.com"),
    (1070, "mitro panut", "mitro_panut@gmail.com"),
    (1106, "ani", "ani@gmail.com"),
    (1107, "santi susanti", "santi_susanti@gmail.com"),
    (1108, "nyaman", "nyaman@gmail.com"),
    (1109, "rusmiyati", "rusmiyati@gmail.com"),
    (1110, "taufik usman", "taufik_usman@gmail.com"),
    (1146, "mitro panut", "mitro_panut@gmail.com"),
    (1147, "rubiyati", "rubiyati@gmail.com"),
    (1148, "supri yanto", "supri_yanto@gmail.com"),
    (1149, "ani paridah", "ani_paridah@gmail.com"),
    (1150, "nina ayu lestari", "nina_ayu_lestari@gmail.com"),
    (1186, "jaemah", "jaemah@gmail.com"),
    (1187, "eka junita", "eka_junita@gmail.com"),
    (1188, "duwi a. fikri", "duwi_a._fikri@gmail.com"),
    (1189, "muhammad akbar rizan", "muhammad_akbar_rizan@gmail.com"),
    (1190, "martono", "martono@gmail.com"),
    (1226, "budiman syahputra", "budiman_syahputra@gmail.com"),
    (1227, "sri nawati", "sri_nawati@gmail.com"),
    (1228, "rakha fico efendi", "rakha_fico_efendi@gmail.com"),
    (1229, "muji syukur", "muji_syukur@gmail.com"),
    (1230, "ismini", "ismini@gmail.com"),
    (1266, "supriyadi", "supriyadi@gmail.com"),
    (1267, "sri khayati", "sri_khayati@gmail.com"),
    (1268, "al fathir rakha abyan", "al_fathir_rakha_abyan@gmail.com"),
    (1269, "herman", "herman@gmail.com"),
    (1270, "tria ningsih", "tria_ningsih@gmail.com"),
]

df = pd.DataFrame(user_data_rinnai, columns=["user_id", "nama", "email"])

df.to_csv("./dataset/user_data_rinnai.csv", index=False)

print("Data pengguna Rinnai telah disimpan dalam file CSV.")
