import pandas as pd

user_data_erigo = [
    (1, "hafizhan shidqi", "hafizhan_shidqi@gmail.com"),
    (2, "gandhi wibowo", "gandhi_wibowo@gmail.com"),
    (3, "aldio mahendra purwandrarto", "aldio_mahendra_purwandrarto@gmail.com"),
    (4, "benny putra", "benny_putra@gmail.com"),
    (5, "vicky vernando dasta", "vicky_vernando_dasta@gmail.com"),
    (41, "yusrika dewi", "yusrika_dewi@gmail.com"),
    (42, "zakiah nurviani", "zakiah_nurviani@gmail.com"),
    (43, "aditya dwi nugraha", "aditya_dwi_nugraha@gmail.com"),
    (44, "afrian djugi", "afrian_djugi@gmail.com"),
    (45, "debby jayadi nugroho", "debby_jayadi_nugroho@gmail.com"),
    # 11-20
    (81, "aidil badri", "aidil_badri@gmail.com"),
    (82, "alfajri", "alfajri@gmail.com"),
    (83, "bayu hasan basyir aljawi", "bayu_hasan_basyir_aljawi@gmail.com"),
    (84, "desi fransiska", "desi_fransiska@gmail.com"),
    (85, "desnando", "desnando@gmail.com"),
    (121, "desy syahputri", "desy_syahputri@gmail.com"),
    (122, "eka wulandari", "eka_wulandari@gmail.com"),
    (123, "ferry ramadhan", "ferry_ramadhan@gmail.com"),
    (124, "firdaus", "firdaus@gmail.com"),
    (125, "hamdani asril", "hamdani_asril@gmail.com"),
    # 21-30
    (161, "indriani saritsha", "indriani_saritsha@gmail.com"),
    (162, "inggar wangi r", "inggar_wangi_r@gmail.com"),
    (163, "mira afriani", "mira_afriani@gmail.com"),
    (164, "muhammad adri", "muhammad_adri@gmail.com"),
    (165, "muhammad alayyubi", "muhammad_alayyubi@gmail.com"),
    (201, "muhammad asri wisnu wardana", "muhammad_asri_wisnu_wardana@gmail.com"),
    (202, "muhammad audi reza islami", "muhammad_audi_reza_islami@gmail.com"),
    (203, "muhammad azmeer", "muhammad_azmeer@gmail.com"),
    (204, "muhammad thoha", "muhammad_thoha@gmail.com"),
    (205, "novi gustiana", "novi_gustiana@gmail.com"),
    # 31-40
    (241, "muhammad sholihan", "muhammad_sholihan@gmail.com"),
    (242, "novita dewi", "novita_dewi@gmail.com"),
    (243, "novri sabli saputra", "novri_sabli_saputra@gmail.com"),
    (244, "pajar bahari", "pajar_bahari@gmail.com"),
    (245, "redha fauziah aziz", "redha_fauziah_aziz@gmail.com"),
    (281, "nurfatrianti", "nurfatrianti@gmail.com"),
    (282, "pikril islami", "pikril_islami@gmail.com"),
    (283, "rikal", "rikal@gmail.com"),
    (284, "riyan hidayat", "riyan_hidayat@gmail.com"),
    (285, "rizki fatama", "rizki_fatama@gmail.com"),
    ## 41-50
    (321, "sugianti", "sugianti@gmail.com"),
    (322, "aris pratama putra", "aris_pratama_putra@gmail.com"),
    (323, "adella", "adella@gmail.com"),
    (324, "widyo sudiro", "widyo_sudiro@gmail.com"),
    (325, "kusniah", "kusniah@gmail.com"),
    (361, "sugianti", "sugianti@gmail.com"),
    (362, "aris pratama putra", "aris_pratama_putra@gmail.com"),
    (363, "adella", "adella@gmail.com"),
    (364, "widyo sudiro", "widyo_sudiro@gmail.com"),
    (365, "kusniah", "kusniah@gmail.com"),
    # 51-60
    (401, "riko hari prasetyo", "riko_hari_prasetyo@gmail.com"),
    (402, "diva al farizky", "diva_al_farizky@gmail.com"),
    (403, "parjo", "parjo@gmail.com"),
    (404, "rumsiyah", "rumsiyah@gmail.com"),
    (405, "dewi sumarni", "dewi_sumarni@gmail.com"),
    (441, "miyanto", "miyanto@gmail.com"),
    (442, "samiyah", "samiyah@gmail.com"),
    (443, "wahyu pratama", "wahyu_pratama@gmail.com"),
    (444, "devina tria ananda", "devina_tria_ananda@gmail.com"),
    (445, "masruri", "masruri@gmail.com"),
    # 61- 70
    (481, "mira mustika", "mira_mustika@gmail.com"),
    (482, "edi suyoto", "edi_suyoto@gmail.com"),
    (483, "rikana nurmala desi", "rikana_nurmala_desi@gmail.com"),
    (484, "zidane dhevan pratama", "zidane_dhevan_pratama@gmail.com"),
    (485, "mariyamah", "mariyamah@gmail.com"),
    (521, "nur qasanah", "nur_qasanah@gmail.com"),
    (522, "andika dwi pangestu", "andika_dwi_pangestu@gmail.com"),
    (523, "mhd. yunus", "andika_dwi_pangestu@gmail.com"),
    (524, "juminah", "juminah@gmail.com"),
    (525, "dwi yuliani", "dwi_yuliani@gmail.com"),
    # 71-80
    (561, "kasman rasim", "kasman_rasim@gmail.com"),
    (562, "marsiti", "marsiti@gmail.com"),
    (563, "susi lestari", "susi_lestari@gmail.com"),
    (564, "narjam", "narjam@gmail.com"),
    (565, "tumiati", "tumiati@gmail.com"),
    (601, "imron mahmudi", "imron_mahmudi@gmail.com"),
    (602, "sumarno", "sumarno@gmail.com"),
    (603, "siti khasana", "siti_khasana@gmail.com"),
    (604, "muhammad alfaqih", "muhammad_alfaqih@gmail.com"),
    (605, "wagiyo", "wagiyo@gmail.com"),
    # 81-90
    (641, "viki kumala putri", "viki_kumala_putri@gmail.com"),
    (642, "vika kumala putri", "vika_kumala_putri@gmail.com"),
    (643, "muhamat saiful safi'i", "muhamat_saiful_safi'i@gmail.com"),
    (644, "warsini", "warsini@gmail.com"),
    (645, "dimaz reza ramadhan", "dimaz_reza_ramadhan@gmail.com"),
    (681, "sarno", "sarno@gmail.com"),
    (682, "giyem", "giyem@gmail.com"),
    (683, "siti khasanah", "siti_khasanah@gmail.com"),
    (684, "andrianto", "andrianto@gmail.com"),
    (685, "tri purwanti", "tri_purwanti@gmail.com"),
    # 91-100
    (721, "nuriah", "nuriah@gmail.com"),
    (722, "irma lestari", "irma_lestari@gmail.com"),
    (723, "nur kholifah", "nur_kholifah@gmail.com"),
    (724, "muhammad abdul rohman", "muhammad_abdul_rohman@gmail.com"),
    (725, "yendra putra", "yendra_putra@gmail.com"),
    (761, "al hakim januario barens", "al_hakim_januario_barens@gmail.com"),
    (762, "amal fatullah", "amal_fatullah@gmail.com"),
    (763, "ayu kusmini", "ayu_kusmini@gmail.com"),
    (764, "yusman", "yusman@gmail.com"),
    (765, "alfia santi sahputri", "alfia_santi_sahputri@gmail.com"),
    # 101 - 110
    (801, "alisa devi saputri", "alisa_devi_saputri@gmail.com"),
    (802, "fauzan adi saputra", "fauzan_adi_saputra@gmail.com"),
    (803, "mariyauddin", "mariyauddin@gmail.com"),
    (804, "swarti", "swarti@gmail.com"),
    (805, "reza indra saputra", "reza_indra_saputra@gmail.com"),
    (841, "lasmini", "lasmini@gmail.com"),
    (842, "sri lestari", "sri_lestari@gmail.com"),
    (843, "mukhlis sariadin", "mukhlis_sariadin@gmail.com"),
    (844, "sukadi", "sukadi@gmail.com"),
    (845, "bintiah", "bintiah@gmail.com"),
    # 111 - 120
    (881, "alfazola", "alfazola@gmail.com"),
    (882, "azza nabilla tasya", "azza_nabilla_tasya@gmail.com"),
    (883, "hafsa nur hafizza", "hafsa_nur_hafizza@gmail.com"),
    (884, "alhadmin", "alhadmin@gmail.com"),
    (885, "dahlia", "dahlia@gmail.com"),
    (921, "m. tolib syahbarul", "m._tolib_syahbarul@gmail.com"),
    (922, "bela novitasari", "bela_novitasari@gmail.com"),
    (923, "muhammad afdal affandi", "muhammad_afdal_affandi@gmail.com"),
    (924, "dedi iswandi", "dedi_iswandi@gmail.com"),
    (925, "ahmad purwito", "ahmad_purwito@gmail.com"),
    # 121-130
    (961, "muhaimin", "muhaimin@gmail.com"),
    (962, "dwi rukiyah", "dwi_rukiyah@gmail.com"),
    (963, "azuwa fatkur alkholif", "azuwa_fatkur_alkholif@gmail.com"),
    (964, "binti", "binti@gmail.com"),
    (965, "andi baskoro", "andi_baskoro@gmail.com"),
    (1001, "bayu istanto", "bayu_istanto@gmail.com"),
    (1002, "indah bunga hati", "indah_bunga_hati@gmail.com"),
    (1003, "waelan", "waelan@gmail.com"),
    (1004, "rastina", "rastina@gmail.com"),
    (1005, "hari kurniawan", "hari_kurniawan@gmail.com"),
    # 131-140
    (1041, "siti mudrikah", "siti_mudrikah@gmail.com"),
    (1042, "indarti", "indarti@gmail.com"),
    (1043, "wahab maulana ramadhan", "wahab_maulana_ramadhan@gmail.com"),
    (1044, "haikal aziz kurniawan", "haikal_aziz_kurniawan@gmail.com"),
    (1045, "ahmad tona", "ahmad_tona@gmail.com"),
    (1081, "salpiah", "salpiah@gmail.com"),
    (1082, "mustaqpirin", "mustaqpirin@gmail.com"),
    (1083, "khairudin", "khairudin@gmail.com"),
    (1084, "khairul ilham", "khairul_ilham@gmail.com"),
    (1085, "yuli yanti", "yuli_yanti@gmail.com"),
    # 141-150
    (1121, "ahmad tona", "ahmad_tona@gmail.com"),
    (1122, "sutomo", "sutomo@gmail.com"),
    (1123, "mariyem", "mariyem@gmail.com"),
    (1124, "setio purwanto", "setio_purwanto@gmail.com"),
    (1125, "tri tugas", "tri_tugas@gmail.com"),
    (1161, "yuli yanti", "yuli_yanti@gmail.com"),
    (1162, "shela nur diana sari", "shela_nur_diana_sari@gmail.com"),
    (1163, "lhailatul istamaroh", "lhailatul_istamaroh@gmail.com"),
    (1164, "sudirman", "sudirman@gmail.com"),
    (1165, "atik winarni", "atik_winarni@gmail.com"),
    # 151-160
    (1201, "abi gail", "abi_gail@gmail.com"),
    (1202, "raudati zuhriyah", "raudati_zuhriyah@gmail.com"),
    (1203, "nirmala syafira", "nirmala_syafira@gmail.com"),
    (1204, "turhadi", "turhadi@gmail.com"),
    (1205, "konah", "konah@gmail.com"),
    (1241, "mustofa", "mustofa@gmail.com"),
    (1242, "somad susanto", "somad_susanto@gmail.com"),
    (1243, "immatul azizah", "immatul_azizah@gmail.com"),
    (1244, "lamsyah purba", "lamsyah_purba@gmail.com"),
    (1245, "roliana silalahi", "roliana_silalahi@gmail.com"),
]


df = pd.DataFrame(user_data_erigo, columns=["user_id", "nama", "email"])

df.to_csv("./dataset/user_data_erigo.csv", index=False)

print("Jumlah: ", len(user_data_erigo))

print("Data pengguna Erigo telah disimpan dalam file CSV.")
