import pandas as pd

user_data_bardi = [
    (36, "tania rahmadhini", "tania_rahmadhini@gmail.com"),
    (37, "tarikhul mahfudz", "tarikhul_mahfudz@gmail.com"),
    (38, "vido idramedi", "vido_idramedi@gmail.com"),
    (39, "wahyu darmawan", "wahyu_darmawan@gmail.com"),
    (40, "yana famana", "yana_famana@gmail.com"),
    (76, "wahyu ernu setiawan", "wahyu_ernu_setiawan@gmail.com"),
    (77, "yofaldi laksmana putra", "yofaldi_laksmana_putra@gmail.com"),
    (78, "zubaidah", "zubaidah@gmail.com"),
    (79, "agus faturrahman", "agus_faturrahman@gmail.com"),
    (80, "agustiando rahmat", "agustiando_rahmat@gmail.com"),
    (116, "amelia novrida", "amelia_novrida@gmail.com"),
    (117, "andre ganda wilaga putra", "andre_ganda_wilaga_putra@gmail.com"),
    (118, "andre oktora", "andre_oktora@gmail.com"),
    (119, "benni setiawan", "benni_setiawan@gmail.com"),
    (120, "deswanto", "deswanto@gmail.com"),
    (156, "dewi cita rani", "dewi_cita_rani@gmail.com"),
    (157, "dewi kartika sari", "dewi_kartika_sari@gmail.com"),
    (158, "dewi shinta octariati", "dewi_shinta_octariati@gmail.com"),
    (159, "firdaus", "firdaus@gmail.com"),
    (160, "fitra andri gunawan", "fitra_andri_gunawan@gmail.com"),
    (196, "fitri meldiani", "fitri_meldiani@gmail.com"),
    (197, "husnul habib", "husnul_habib@gmail.com"),
    (198, "irfani dwi ayu riski", "irfani_dwi_ayu_riski@gmail.com"),
    (199, "irpandi kurniawan", "irpandi_kurniawan@gmail.com"),
    (200, "kurniawan eka putra", "kurniawan_eka_putra@gmail.com"),
    (236, "irwan ahmad gafur", "irwan_ahmad_gafur@gmail.com"),
    (237, "isa ismail", "isa_ismail@gmail.com"),
    (238, "kurniawan rosman a", "kurniawan_rosman_a@gmail.com"),
    (239, "muhammad azmy", "muhammad_azmy@gmail.com"),
    (240, "muhammad ilham", "muhammad_ilham@gmail.com"),
    (276, "muhammad oki", "muhammad_oki@gmail.com"),
    (277, "muhammad ridho ardonis", "muhammad_ridho_ardonis@gmail.com"),
    (278, "muhammad rizqi muttaqin", "muhammad_rizqi_muttaqin@gmail.com"),
    (279, "muhammad setyo", "muhammad_setyo@gmail.com"),
    (280, "nur aulia hasanah", "nur_aulia_hasanah@gmail.com"),
    (316, "reza andika ramadhan", "reza_andika_ramadhan@gmail.com"),
    (317, "slamet", "slamet@gmail.com"),
    (318, "erna", "erna@gmail.com"),
    (319, "gilang aditia", "gilang_aditia@gmail.com"),
    (320, "suherianto", "suherianto@gmail.com"),
    (356, "suwarti", "suwarti@gmail.com"),
    (357, "krisdan fauzi", "krisdan_fauzi@gmail.com"),
    (358, "khasanah dwi fauziah", "khasanah_dwi_fauziah@gmail.com"),
    (359, "ainun isnaini fauziati", "ainun_isnaini_fauziati@gmail.com"),
    (360, "m. rais tri wahyudi", "m._rais_tri_wahyudi@gmail.com"),
    (396, "meriyanti", "meriyanti@gmail.com"),
    (397, "erna lestari", "erna_lestari@gmail.com"),
    (398, "asef saifulloh", "asef_saifulloh@gmail.com"),
    (399, "jonianto", "jonianto@gmail.com"),
    (400, "mujiati", "mujiati@gmail.com"),
    (436, "nugroho", "nugroho@gmail.com"),
    (437, "kusriyati", "kusriyati@gmail.com"),
    (438, "vika apriliana n. a", "vika_apriliana_n._a@gmail.com"),
    (439, "bela octavia ramadani", "bela_octavia_ramadani@gmail.com"),
    (440, "pri santoso", "pri_santoso@gmail.com"),
    (476, "umi muslimah", "umi_muslimah@gmail.com"),
    (477, "elisa anjani", "elisa_anjani@gmail.com"),
    (478, "meila nurhidayati", "meila_nurhidayati@gmail.com"),
    (479, "santoso", "santoso@gmail.com"),
    (480, "tumi", "tumi@gmail.com"),
    (516, "karno", "karno@gmail.com"),
    (517, "asmunah", "asmunah@gmail.com"),
    (518, "danang wahyu ananda", "danang_wahyu_ananda@gmail.com"),
    (519, "syamsul huda", "syamsul_huda@gmail.com"),
    (520, "tumirah", "tumirah@gmail.com"),
    (556, "meysa nasa", "meysa_nasa@gmail.com"),
    (557, "eram", "eram@gmail.com"),
    (558, "khotijah", "khotijah@gmail.com"),
    (559, "era satiti", "era_satiti@gmail.com"),
    (560, "rina pangastuti", "rina_pangastuti@gmail.com"),
    (596, "komarudin", "komarudin@gmail.com"),
    (597, "agus riyanto", "agus_riyanto@gmail.com"),
    (598, "m. muhsin as ari", "m._muhsin_as_ari@gmail.com"),
    (599, "indah kurnia sari", "indah_kurnia_sari@gmail.com"),
    (600, "mukhammad 'ainurrido", "mukhammad_'ainurrido@gmail.com"),
    (636, "kasyani", "kasyani@gmail.com"),
    (637, "m. arif harfiyanto", "m._arif_harfiyanto@gmail.com"),
    (638, "novia nurhayati", "novia_nurhayati@gmail.com"),
    (639, "mansyur", "mansyur@gmail.com"),
    (640, "giarsih", "giarsih@gmail.com"),
    (676, "nadhirotul khusniah", "nadhirotul_khusniah@gmail.com"),
    (677, "dewi masitoh", "dewi_masitoh@gmail.com"),
    (678, "ach. moehaimin alwi", "ach._moehaimin_alwi@gmail.com"),
    (679, "siti aisyah", "siti_aisyah@gmail.com"),
    (680, "muhammad faizin alwi", "muhammad_faizin_alwi@gmail.com"),
    (716, "sukarmin", "sukarmin@gmail.com"),
    (717, "saniri", "saniri@gmail.com"),
    (718, "firda ramadan", "firda_ramadan@gmail.com"),
    (719, "fauzi hidayat", "fauzi_hidayat@gmail.com"),
    (720, "ahmad suyadi", "ahmad_suyadi@gmail.com"),
    #
    (756, "mardani satra", "mardani_satra@gmail.com"),
    (757, "fitria wulandari", "fitria_wulandari@gmail.com"),
    (758, "bastiur", "bastiur@gmail.com"),
    (759, "endah susanti", "endah_susanti@gmail.com"),
    (760, "olivvia febby santika", "olivvia_febby_santika@gmail.com"),
    (796, "jumali", "jumali@gmail.com"),
    (797, "irma indriyani", "irma_indriyani@gmail.com"),
    (798, "suratno", "suratno@gmail.com"),
    (799, "nuramsah", "nuramsah@gmail.com"),
    (800, "diana nur fhaisah", "diana_nur_fhaisah@gmail.com"),
    (836, "warhan", "warhan@gmail.com"),
    (837, "halima tussa'dia", "halima_tussa'dia@gmail.com"),
    (838, "syavira hanzuneira", "syavira_hanzuneira@gmail.com"),
    (839, "irwan efendi", "irwan_efendi@gmail.com"),
    (840, "sugiarto", "sugiarto@gmail.com"),
    (876, "ujang umin ruhdiansyah", "ujang_umin_ruhdiansyah@gmail.com"),
    (877, "dede rumyati", "dede_rumyati@gmail.com"),
    (878, "eka rosmawati", "eka_rosmawati@gmail.com"),
    (879, "lely lutfiah sungkar", "lely_lutfiah_sungkar@gmail.com"),
    (880, "ivan gustomi", "ivan_gustomi@gmail.com"),
    (916, "suryani", "suryani@gmail.com"),
    (917, "tatik dwi ambarwati", "tatik_dwi_ambarwati@gmail.com"),
    (918, "ima listiani", "ima_listiani@gmail.com"),
    (919, "sujono", "sujono@gmail.com"),
    (920, "marini", "marini@gmail.com"),
    (956, "alfiyatu zahroh", "alfiyatu_zahroh@gmail.com"),
    (957, "miftakhul qolbi", "miftakhul_qolbi@gmail.com"),
    (958, "abdullah afif azzuhri", "abdullah_afif_azzuhri@gmail.com"),
    (959, "afifah azzahroh", "afifah_azzahroh@gmail.com"),
    (960, "kevin kenzi al firmansyah", "kevin_kenzi_al_firmansyah@gmail.com"),
    (996, "wagino", "wagino@gmail.com"),
    (997, "sri rejeki", "sri_rejeki@gmail.com"),
    (998, "diky handriansyah", "diky_handriansyah@gmail.com"),
    (999, "giono", "giono@gmail.com"),
    (1000, "ismiyati", "ismiyati@gmail.com"),
    (1036, "tumidjo", "tumidjo@gmail.com"),
    (1037, "sumarni", "sumarni@gmail.com"),
    (1038, "aprilia rahmawati", "aprilia_rahmawati@gmail.com"),
    (1039, "febi ayu lestari", "febi_ayu_lestari@gmail.com"),
    (1040, "gunawan", "gunawan@gmail.com"),
    (1076, "paryono", "paryono@gmail.com"),
    (1077, "sukatmi", "sukatmi@gmail.com"),
    (1078, "eva apriyani", "eva_apriyani@gmail.com"),
    (1079, "asiva nur aini", "asiva_nur_aini@gmail.com"),
    (1080, "m. amin", "m._amin@gmail.com"),
    (1116, "gunawan", "gunawan@gmail.com"),
    (1117, "siti mudrikah", "siti_mudrikah@gmail.com"),
    (1118, "indarti", "indarti@gmail.com"),
    (1119, "wahab maulana ramadhan", "wahab_maulana_ramadhan@gmail.com"),
    (1120, "haikal aziz kurniawan", "haikal_aziz_kurniawan@gmail.com"),
    (1156, "m. amin", "m._amin@gmail.com"),
    (1157, "salpiah", "salpiah@gmail.com"),
    (1158, "mustaqpirin", "mustaqpirin@gmail.com"),
    (1159, "khairudin", "khairudin@gmail.com"),
    (1160, "khairul ilham", "khairul_ilham@gmail.com"),
    (1196, "hani atun", "hani_atun@gmail.com"),
    (1197, "riska sundari", "riska_sundari@gmail.com"),
    (1198, "sabrina fatmawati", "sabrina_fatmawati@gmail.com"),
    (1199, "abdul jalil", "abdul_jalil@gmail.com"),
    (1200, "sulastri", "sulastri@gmail.com"),
    (1236, "sugianto", "sugianto@gmail.com"),
    (1237, "deni primawan", "deni_primawan@gmail.com"),
    (1238, "muhammad yusuf", "muhammad_yusuf@gmail.com"),
    (1239, "niwan", "niwan@gmail.com"),
    (1240, "siti masithoh", "siti_masithoh@gmail.com"),
    (1276, "dion aldi setiawan", "dion_aldi_setiawan@gmail.com"),
    (1277, "teguh ramadhan", "teguh_ramadhan@gmail.com"),
    (1278, "nurokhmad ikhwandi", "nurokhmad_ikhwandi@gmail.com"),
    (1279, "siti maryatun", "siti_maryatun@gmail.com"),
    (1280, "muhammad fajri maulana", "muhammad_fajri_maulana@gmail.com"),
]

df = pd.DataFrame(user_data_bardi, columns=["user_id", "nama", "email"])

df.to_csv("./dataset/user_data_bardi.csv", index=False)


print("Panjang: ", len(user_data_bardi))

print("Data pengguna Bardi telah disimpan dalam file CSV.")
