# Generated by Django 3.2.10 on 2023-11-04 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0003_alter_review_comment'),
        ('review', '0003_review_sentiment'),
    ]

    operations = [
    ]
